я
htmlacademy-htmlcss/1540033-sedona-29 pull request #2
Opened 2020-09-12 18:38 UTC by AleksandraOparina

2020-09-13 11:31 UTC, craz3r requested changes

2020-09-13 11:31 UTC, craz3r commented on index.html
> +        <h1>Седона</h1>
Заголовок первого уровня обычно находится в теге main, логотип обычно им не делают.

2020-09-13 11:31 UTC, craz3r commented on index.html
> +              <li> <a href="foto&video.html">Фото и видео</a> </li>
символ амперсанда в адресном пути недопустим, так как он разделяет сам адрес от параметров запроса

2020-09-13 11:31 UTC, craz3r commented on index.html
> +               <h2>Добро пожаловать в Седону</h2>
Лучше поместить заголовок первого уровня здесь

2020-09-13 11:31 UTC, craz3r commented on index.html
> +        </section>
Отсутствует открывающий тег section

2020-09-13 11:31 UTC, craz3r commented on index.html
> +                  <header>
2 тега header не могут размещаться на одном уровне вложенности, если хочется поместить здесь header, то лучше вынести весь основной контент страницы (тот что между header и footer в тег main)

2020-09-13 11:31 UTC, craz3r commented on index.html
> +           <h3>Настоящий городок</h3>
Каждый элемент блока преимуществ лучше вынести в отдельный тег, для разделяемости и большей читабельности. Сами же преимущества (те, что начинаются с "жилье" лучше оформить в список, так как эти элементы однотипны

2020-09-13 11:31 UTC, craz3r commented on index.html
> +               <li>
Тег li использован вне тега ul

2020-09-13 11:31 UTC, craz3r commented on index.html
> +               <h3>Там есть <br> мост дьявола</h3>
Блок "там есть мост дьявола" логически не является элементом списка наряду с элементами "небольльшая площадь, красивая дорога..." его лучше вынести из списка в отдельный тег.

2020-09-13 11:31 UTC, craz3r commented on index.html
> +          </ul>
Отсутствует открывающий тег ul

2020-09-13 11:31 UTC, craz3r commented on index.html
> +          <h2>Поиск гостиницы в седоне</h2>
Этот элемент является кнопкой переключающей всплывающее окно с формой

2020-09-13 11:31 UTC, craz3r commented on index.html
> +          <p>
Отсутствует закрывающий тег p

2020-09-13 11:31 UTC, craz3r commented on index.html
> +                       <a href="https://htmlacademy.ru">
Здесь должна быть размещена ссылка на интенсив

2020-09-13 16:41 UTC, AleksandraOparina commented
поправила, вроде как

2020-09-14 06:46 UTC, craz3r requested changes

2020-09-14 06:46 UTC, craz3r commented on index.html
> +
Ты перенесла заголовок в main, но в макете в хедере все есть надпись Sedona, это по сути логотип, его надо добавить

2020-09-14 06:46 UTC, craz3r commented on index.html
> +                  <li><h4>Жильё</h4></li>
Этот элемент сам по себе не является самостоятельным элементом списка

2020-09-14 06:46 UTC, craz3r commented on index.html
> +                  <li><h4>Жильё</h4></li>
Его следует объединить с параграфом ниже

2020-09-14 06:46 UTC, craz3r commented on index.html
> +                  <h3>Там есть <br> мост дьявола</h3>
Этот элемент по структуре такой же как и "Настоящий городок", и по структуре тегов должен быть таким же (убрать лишний section выше)

2020-09-14 06:46 UTC, craz3r commented on index.html
> +                    <section>
section здесь не нужен, блок слишком маленький

2020-09-14 06:46 UTC, craz3r commented on index.html
> +          <h2><button type="button">Поиск гостиницы в Седоне</button></h2>
Слишком много h2 на странице, может следует заменить на h3?

2020-09-14 06:46 UTC, craz3r commented on index.html
> +          <section>
section здесь необязателен, блок не тянет на большой кусок самостоятельного контента

2020-09-14 06:46 UTC, craz3r requested changes

2020-09-14 06:46 UTC, craz3r commented on index.html
> +              <a href="https://htmlacademy.ru">HTML Academy</a>
Здесь должна быть ссылка на интенсив

2020-09-14 06:50 UTC, craz3r commented
Нужно привести отступы в файле к единому формату см [критерий Б15](https://up.htmlacademy.ru/htmlcss/29/criteries#b15)

2020-09-18 09:28 UTC, craz3r approved these changes

2020-09-18 09:28 UTC, craz3r commented on index.html
> +          <header class="main-header">
Не хватает логотипа

2020-09-18 09:28 UTC, craz3r commented on index.html
> +                 <div> <img alt="Мост дьявола" height="800" </div>
тег img не закрыт

2020-09-18 09:28 UTC, craz3r commented on index.html
> +                <div> <img alt="Настоящий городок" height="256" src="city.jpg" width="800"> </div>
тег img закрыт неправильно

2020-09-18 09:28 UTC, craz3r commented on index.html
> +          <img alt="Добро пожаловать в Седону" height="509" src="img/welcome.png" width="1200">
тег img закрыт неправильно

2020-09-18 09:28 UTC, merged